title: Vert_EX
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'A dojo for ex-Vertican information developers'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
